---
apiVersion: v1
kind: Pod
metadata:
  name: devicepluginpod
  namespace: kube-system
spec:
  containers:
  - name: deviceplugin
    image: localhost:5000/deviceplugin:latest
    securityContext:
      runAsUser: 0
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: device-plugins
      mountPath: /var/lib/kubelet/device-plugins
  volumes:
  - name: device-plugins
    hostPath:
      path: /var/lib/kubelet/device-plugins
